spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_test
    username: postgres
    password: Busra12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true