spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: Busra12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  #ilk başta create daha sonra her zaman update kalacak
    show-sql: true